export const images = {
  logo: require('../assets/images/logo.png'),
  Forwardbutton: require('../assets/images/Forwardbutton.png'),
  BlueCircle: require('../assets/images/BlueCircle.png'),
  GreyCircle: require('../assets/images/GreyCircle.png'),
  Star: require('../assets/images/Star.png'),
  User: require('../assets/images/User.png'),
  GreyBox: require('../assets/images/GreyBox.png'),
  BlueBox: require('../assets/images/BlueBox.png'),
  AppleIcon: require('../assets/images/AppleIcon.png'),
  LinkedinIcon: require('../assets/images/LinkedinIcon.png'),
  Shield: require('../assets/images/Shield.png'),
  BlueBg: require('../assets/images/BlueBg.png'),
  menu: require('../assets/images/menu.png'),
  ChatIcon: require('../assets/images/ChatIcon.png'),
  bellIcon: require('../assets/images/bellIcon.png'),
  User1: require('../assets/images/User1.png'),
  fbIconWhite: require('../assets/images/fbIconWhite.png'),
  instaIconWhite: require('../assets/images/instaIconWhite.png'),
  LinkedinIconWhite: require('../assets/images/LinkedinIconWhite.png'),
  TiktokIconWhite: require('../assets/images/TiktokIconWhite.png'),
  twiterIconWhite: require('../assets/images/twiterIconWhite.png'),
  Coins: require('../assets/images/Coins.png'),
  Edit: require('../assets/images/edit.png'),
  PaperPlain: require('../assets/images/PaperPlain.png'),
  back: require('../assets/images/back.png'),
  CalendarIcon: require('../assets/images/CalendarIcon.png'),
  searchIcon: require('../assets/images/searchIcon.png'),
  IntroCard: require('../assets/images/IntroCard.png'),
  error: require('../assets/images/error.png'),
  MsgSendBtn: require('../assets/images/MsgSendBtn.png'),
  cross: require('../assets/images/cross.png'),
  // editExperience: require('../assets/images/edit.png'),
  hi: require('../assets/images/hi.png'),
  activeCheck: require('../assets/images/activeCheck.png'),
  nonActiveCheck: require('../assets/images/nonActiveCheck.png'),
};
